=== junpee/HSD_Prototype/integrated-repository-webapp/WebContent/WEB-INF/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="configs" type="configsType"/>
	
	<xs:complexType name="configsType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="config" type="configType"/>
			<xs:element name="config-group" type="configGroupType"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="configGroupType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="config" type="configType"/>
			<xs:element name="config-group" type="configGroupType"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="configType">
		<xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="value" type="xs:string"/>
			<xs:element name="list" type="listType"/>
			<xs:element name="map" type="mapType"/>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="listType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="value" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="mapType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="entry" type="entryType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="entryType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="key" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
</xs:schema>

=== junpee/HSD_Prototype/integrated-repository-webapp/WebContent/WEB-INF/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<configs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="configuration.xsd">

	<!-- Configurations for Built-in Generators -->


	<!-- TemplatedHelloWorldGenerators -->
	<config-group name="TemplatedHelloWorldGenerator">
		<config name="templateResourcePath">
			<value>template/generator/builtin/sample/templated-hello-world.flt</value>
		</config>
	</config-group>
	<config-group name="TemplatedDdlGeneratorDB2">
		<config name="templateResourcePath">
			<value>template/generator/builtin/ddl/datamodel-entity-to-ddl-for-db2.ftl</value>
		</config>
	</config-group>
	<config-group name="TemplatedDdlGeneratorOracle">
		<config name="templateResourcePath">
			<value>template/generator/builtin/ddl/datamodel-entity-to-ddl-for-oracle.ftl</value>
		</config>
	</config-group>

	<!-- Configurations for Built-in Uploaders -->


	<!-- Configurations for Built-in Schedulers -->


	<!-- User Defined -->


</configs>
